// this was generated by Grok (lol)

/**
 * Configuration settings for Converse.js.
 * This interface defines all possible configuration options for customizing the behavior and appearance of Converse.js.
 *
 * @interface ConverseConfig
 */
export interface ConverseConfig {
	// missing from grok response for some reason;
	whitelisted_plugins?: string[];
	password?: string;

	/**
	 * Domains allowed for audio embedding. If null, all domains are allowed.
	 */
	allowed_audio_domains?: string[] | null;

	/**
	 * Domains allowed for image embedding. If null, all domains are allowed.
	 */
	allowed_image_domains?: string[] | null;

	/**
	 * Domains allowed for video embedding. If null, all domains are allowed.
	 */
	allowed_video_domains?: string[] | null;

	/**
	 * Authentication method to use.
	 * @default 'login'
	 */
	authentication?: "login" | "external" | "anonymous" | "prebind";

	/**
	 * Allow privileged users to run XEP-0050 Ad-Hoc commands.
	 * @default true
	 */
	allow_adhoc_commands?: boolean;

	/**
	 * Enable chatroom bookmarks functionality.
	 * @default true
	 */
	allow_bookmarks?: boolean;

	/**
	 * Allow users to remove roster contacts.
	 * @default true
	 */
	allow_contact_removal?: boolean;

	/**
	 * Allow users to add one another as contacts.
	 * @default true
	 */
	allow_contact_requests?: boolean;

	/**
	 * Allow users to resize chats by dragging edges.
	 * @default true
	 */
	allow_dragresize?: boolean;

	/**
	 * Allow users to log out.
	 * @default true
	 */
	allow_logout?: boolean;

	/**
	 * Configure last message correction (LMC) feature.
	 * @default 'all'
	 */
	allow_message_corrections?: "all" | "last" | false;

	/**
	 * Determine who can retract messages.
	 * @default 'all'
	 */
	allow_message_retraction?: "all" | "own" | "moderator" | false;

	/**
	 * Enable support for XEP-0393 Message Styling hints.
	 * @default true
	 */
	allow_message_styling?: boolean;

	/**
	 * Allow users to be invited to join MUC chatrooms.
	 * @default true
	 */
	allow_muc_invitations?: boolean;

	/**
	 * Allow receiving messages from users not in the roster.
	 * @default false
	 */
	allow_non_roster_messaging?: boolean;

	/**
	 * Allow public bookmarks if private PEP/PubSub nodes are not supported.
	 * @default false
	 */
	allow_public_bookmarks?: boolean;

	/**
	 * Allow XMPP account registration.
	 * @default true
	 */
	allow_registration?: boolean;

	/**
	 * Allow Converse to change the browser URL bar.
	 * @default true
	 */
	allow_url_history_change?: boolean;

	/**
	 * Allow users to decide if Converse is trusted in the browser.
	 * @default true
	 */
	allow_user_trust_override?: boolean | "off";

	/**
	 * Maximum archived messages returned per query.
	 * @default 50
	 */
	archived_messages_page_size?: number;

	/**
	 * Automatically fill gaps in chat history.
	 * @default true
	 */
	auto_fill_history_gaps?: boolean;

	/**
	 * Automatically focus the message input area.
	 * @default true
	 */
	auto_focus?: boolean;

	/**
	 * Fetch list of rooms on the server.
	 * @default false
	 */
	auto_list_rooms?: boolean;

	/**
	 * Automatically log the user in.
	 * @default false
	 */
	auto_login?: boolean;

	/**
	 * Seconds after which the user's presence becomes 'away'.
	 * @default 0
	 */
	auto_away?: number;

	/**
	 * Seconds after which the user's presence becomes 'extended away'.
	 * @default 0
	 */
	auto_xa?: number;

	/**
	 * Automatically reconnect if the connection drops.
	 * @default false
	 */
	auto_reconnect?: boolean;

	/**
	 * Automatically register nickname in groupchats.
	 * @default 'unregister'
	 */
	auto_register_muc_nickname?: boolean | "unregister";

	/**
	 * Automatically subscribe back to contact requests.
	 * @default false
	 */
	auto_subscribe?: boolean;

	/**
	 * Automatically join a chatroom on invite.
	 * @default false
	 */
	auto_join_on_invite?: boolean;

	/**
	 * List of JIDs for private chats to auto-join.
	 * @default []
	 */
	auto_join_private_chats?: string[];

	/**
	 * List of rooms to auto-join.
	 * @default []
	 */
	auto_join_rooms?: Array<{ jid: string; nick?: string; minimized?: boolean } | string>;

	/**
	 * Plugins that will not be initialized.
	 * @default []
	 */
	blacklisted_plugins?: string[];

	/**
	 * URL of the BOSH connection manager.
	 * @default undefined
	 */
	bosh_service_url?: string;

	/**
	 * Clear cached data on logout.
	 * @default false
	 */
	clear_cache_on_logout?: boolean;

	/**
	 * Clear cached messages on reconnection.
	 * @default false
	 * @deprecated This feature will likely be removed in future versions.
	 */
	clear_messages_on_reconnection?: boolean;

	/**
	 * JIDs to ignore for chat state notifications.
	 * @default []
	 */
	chatstate_notification_blacklist?: string[];

	/**
	 * Options passed to Strophe.Connection.
	 * @default {}
	 */
	connection_options?: Record<string, any>;

	/**
	 * URL to fetch login credentials from.
	 * @default null
	 */
	credentials_url?: string;

	/**
	 * Seconds to wait before sending CSI 'inactive'.
	 * @default 0
	 */
	csi_waiting_time?: number;

	/**
	 * Theme used in dark mode.
	 * @default 'dracula'
	 */
	dark_theme?: string;

	/**
	 * Default domain for user JIDs.
	 * @default undefined
	 */
	default_domain?: string;

	/**
	 * Discover Websocket or BOSH URLs via XEP-0156.
	 * @default true
	 */
	discover_connection_methods?: boolean;

	/**
	 * Placeholder for domain input in registration form.
	 * @default 'e.g. conversejs.org'
	 */
	domain_placeholder?: string;

	/**
	 * Top margin for chatbox resizing.
	 * @default 0
	 */
	dragresize_top_margin?: number;

	/**
	 * Embed media players from 3rd party sites.
	 * @default true
	 */
	embed_3rd_party_media_players?: boolean;

	/**
	 * Categories for emoji picker.
	 */
	emoji_categories?: Record<string, string | null>;

	/**
	 * Labels for emoji categories.
	 */
	emoji_categories_label?: Record<string, string>;

	/**
	 * URL for emoji image files.
	 * @default 'https://twemoji.maxcdn.com/2/'
	 */
	emoji_image_path?: string;

	/**
	 * Enable XEP-0357 push notifications for MUCs.
	 * @default false
	 */
	enable_muc_push?: boolean;

	/**
	 * Enable roster versioning.
	 * @default true
	 */
	enable_roster_versioning?: boolean;

	/**
	 * Enable XEP-0198 Stream Management.
	 * @default true
	 */
	enable_smacks?: boolean;

	/**
	 * Fetch headers of URLs to determine media type.
	 * @default false
	 */
	fetch_url_headers?: boolean;

	/**
	 * Filter messages by resource.
	 * @default false
	 */
	filter_by_resource?: boolean;

	/**
	 * Query parameters to remove from URLs.
	 * @default null
	 */
	filter_url_query_params?: string | string[];

	/**
	 * Regex for extracting geo coordinates.
	 */
	geouri_regex?: RegExp;

	/**
	 * Replacement string for geo-URIs.
	 * @default 'https://www.openstreetmap.org/?mlat=$1&mlon=$2#map=18/$1/$2'
	 */
	geouri_replacement?: string;

	/**
	 * Lazily load vCards.
	 * @default true
	 */
	lazy_load_vcards?: boolean;

	/**
	 * Logging level.
	 * @default 'info'
	 */
	loglevel?: "debug" | "info" | "warn" | "error" | "fatal";

	/**
	 * Hide participants list in MUC by default.
	 * @default false
	 */
	hide_muc_participants?: boolean;

	/**
	 * Hide offline users in roster.
	 * @default false
	 */
	hide_offline_users?: boolean;

	/**
	 * Locale/language to use.
	 * @default undefined
	 */
	i18n?: string;

	/**
	 * Seconds after which idle presence is sent.
	 * @default 300
	 */
	idle_presence_timeout?: number;

	/**
	 * Regex for URLs to consider as images.
	 * @default null
	 */
	image_urls_regex?: RegExp;

	/**
	 * Jabber ID of the current user.
	 * @default undefined
	 */
	jid?: string;

	/**
	 * Keep the user logged in across page loads.
	 * @default true
	 */
	keepalive?: boolean;

	/**
	 * List of supported locales.
	 */
	locales?: string[];

	/**
	 * Lock the domain for user JIDs.
	 * @default undefined
	 */
	locked_domain?: string;

	/**
	 * Lock the MUC domain.
	 * @default false
	 */
	locked_muc_domain?: boolean | "hidden";

	/**
	 * Lock the MUC nickname.
	 * @default false
	 */
	locked_muc_nickname?: boolean;

	/**
	 * Request all pages of archived messages.
	 * @default false
	 */
	mam_request_all_pages?: boolean;

	/**
	 * Types of hats to display in MUC.
	 * @default ['xep317']
	 */
	muc_hats?: string[];

	/**
	 * Minimum characters for nickname autocomplete.
	 * @default 0
	 */
	muc_mention_autocomplete_min_chars?: number;

	/**
	 * Filter method for MUC participants autocomplete.
	 * @default 'contains'
	 */
	muc_mention_autocomplete_filter?: "contains" | "starts_with";

	/**
	 * Show avatars in MUC participants autocomplete.
	 * @default true
	 */
	muc_mention_autocomplete_show_avatar?: boolean;

	/**
	 * Default archiving preference.
	 * @default undefined
	 */
	message_archiving?: "never" | "always" | "roster";

	/**
	 * Timeout for message archiving requests.
	 * @default 20000
	 */
	message_archiving_timeout?: number;

	/**
	 * Maximum characters allowed in a chat message.
	 * @default 0
	 */
	message_limit?: number;

	/**
	 * Disable assigning affiliations/roles in moderator tools.
	 * @default false
	 */
	modtools_disable_assign?: boolean | string[];

	/**
	 * Disable querying affiliations/roles in moderator tools.
	 * @default []
	 */
	modtools_disable_query?: string[];

	/**
	 * Clear messages when leaving a MUC.
	 * @default true
	 * @deprecated This feature will likely be removed in future versions.
	 */
	muc_clear_messages_on_leave?: boolean;

	/**
	 * Disable moderator slash commands.
	 * @default false
	 */
	muc_disable_slash_commands?: boolean | string[];

	/**
	 * Default MUC domain.
	 * @default undefined
	 */
	muc_domain?: string;

	/**
	 * Fetch member lists for MUC.
	 * @default true
	 */
	muc_fetch_members?: boolean | string[];

	/**
	 * Group MUCs by domain.
	 * @default false
	 */
	muc_grouped_by_domain?: boolean;

	/**
	 * Maximum stanzas to show in MUC history.
	 * @default undefined
	 */
	muc_history_max_stanzas?: number;

	/**
	 * Create instant/dynamic rooms.
	 * @default true
	 */
	muc_instant_rooms?: boolean;

	/**
	 * Use JID node as nickname in MUC.
	 * @default false
	 */
	muc_nickname_from_jid?: boolean;

	/**
	 * JID of MUC search service.
	 * @default 'api@search.jabber.network'
	 */
	muc_search_service?: string;

	/**
	 * Send presence probes in MUC.
	 * @default false
	 */
	muc_send_probes?: boolean;

	/**
	 * Respect autojoin attribute of bookmarks.
	 * @default true
	 */
	muc_respect_autojoin?: boolean;

	/**
	 * Regex for valid room IDs.
	 * @default null
	 */
	muc_roomid_policy?: RegExp;

	/**
	 * Hint for room ID policy.
	 * @default null
	 */
	muc_roomid_policy_hint?: string;

	/**
	 * Info messages to show in MUC.
	 */
	muc_show_info_messages?: string[];

	/**
	 * Show logs before joining MUC.
	 * @default false
	 */
	muc_show_logs_before_join?: boolean;

	/**
	 * Subscribe to Room Activity Indicators.
	 * @default false
	 */
	muc_subscribe_to_rai?: boolean;

	/**
	 * Nickname for the current user.
	 * @default undefined
	 */
	nickname?: string;

	/**
	 * Notify for all messages in rooms.
	 * @default false
	 */
	notify_all_room_messages?: boolean | string[];

	/**
	 * Delay for desktop notifications.
	 * @default 5000
	 */
	notification_delay?: number;

	/**
	 * Icon for notifications.
	 * @default 'logo/conversejs-filled.svg'
	 */
	notification_icon?: string;

	/**
	 * Notify for nicknames without XEP-0372 references.
	 * @default false
	 */
	notify_nicknames_without_references?: boolean;

	/**
	 * OAuth providers for login.
	 * @default []
	 */
	oauth_providers?: Array<{ [key: string]: string }>;

	/**
	 * Use OMEMO encryption by default.
	 * @default false
	 */
	omemo_default?: boolean;

	/**
	 * Interval for pinging the server.
	 * @default 60
	 */
	ping_interval?: number;

	/**
	 * Play notification sounds.
	 * @default false
	 */
	play_sounds?: boolean;

	/**
	 * URL to fetch BOSH tokens for prebind.
	 * @default null
	 */
	prebind_url?: string;

	/**
	 * Priority for presence stanzas.
	 * @default 0
	 */
	priority?: number;

	/**
	 * Link to XMPP providers directory.
	 * @default 'https://xmpp.net/directory.php'
	 */
	providers_link?: string;

	/**
	 * Path to assets like images and sounds.
	 * @default '/dist/'
	 */
	assets_path?: string;

	/**
	 * Store for persistent data.
	 * @default 'IndexedDB'
	 */
	persistent_store?: "localStorage" | "IndexedDB" | "sessionStorage" | "BrowserExtLocal" | "BrowserExtSync";

	/**
	 * Prune messages above this count.
	 * @default undefined
	 */
	prune_messages_above?: number;

	/**
	 * When to prune messages.
	 * @default 'unscrolled'
	 */
	pruning_behavior?: "unscrolled" | "scrolled";

	/**
	 * Push notification app servers.
	 * @default []
	 */
	push_app_servers?: Array<{ jid: string; node?: string; secret?: string; disable?: boolean }>;

	/**
	 * Domain for automatic registration form fetching.
	 * @default ''
	 */
	registration_domain?: string;

	/**
	 * Render media URLs.
	 * @default true
	 */
	render_media?: boolean | string[];

	/**
	 * Reuse SCRAM keys for authentication.
	 * @default true
	 */
	reuse_scram_keys?: boolean;

	/**
	 * Whitelist for room config options.
	 * @default []
	 */
	roomconfig_whitelist?: string[];

	/**
	 * Root document for rendering.
	 * @default window.document
	 */
	root?: Document;

	/**
	 * Show roster groups.
	 * @default true
	 */
	roster_groups?: boolean;

	/**
	 * Languages that are right-to-left.
	 * @default ["ar", "fa", "he", "ug"]
	 */
	rtl_langs?: string[];

	/**
	 * Send chat state notifications.
	 * @default true
	 */
	send_chat_state_notifications?: boolean | string[];

	/**
	 * Send chat markers.
	 * @default ['received', 'displayed', 'acknowledged']
	 */
	send_chat_markers?: string[];

	/**
	 * Show background with Converse logo.
	 * @default true
	 */
	show_background?: boolean;

	/**
	 * Show chat state notifications.
	 * @default false
	 */
	show_chat_state_notifications?: boolean;

	/**
	 * Show client info icon.
	 * @default true
	 */
	show_client_info?: boolean;

	/**
	 * Show input for connection URL.
	 * @default false
	 */
	show_connection_url_input?: boolean;

	/**
	 * Show controlbox by default.
	 * @default false
	 */
	show_controlbox_by_default?: boolean;

	/**
	 * Show desktop notifications.
	 * @default true
	 */
	show_desktop_notifications?: boolean | "all";

	/**
	 * Show author's avatar in messages.
	 * @default true
	 */
	show_message_avatar?: boolean;

	/**
	 * Show images inline in chats.
	 * @default true
	 */
	show_images_inline?: boolean;

	/**
	 * Show warning when retracting messages.
	 * @default true
	 */
	show_retraction_warning?: boolean;

	/**
	 * Show self in roster.
	 * @default true
	 */
	show_self_in_roster?: boolean;

	/**
	 * Show send button in chat.
	 * @default true
	 */
	show_send_button?: boolean;

	/**
	 * Show unread messages counter in tab.
	 * @default true
	 */
	show_tab_notifications?: boolean;

	/**
	 * Allow only one chat.
	 * @default false
	 */
	singleton?: boolean;

	/**
	 * Max unacked stanzas for XEP-0198.
	 * @default 5
	 */
	smacks_max_unacked_stanzas?: number;

	/**
	 * Path to sound files.
	 * @default '${assets_path}/sounds/'
	 */
	sounds_path?: string;

	/**
	 * Timeout for stanza responses.
	 * @default 20000
	 */
	stanza_timeout?: number;

	/**
	 * Make controlbox sticky.
	 * @default false
	 */
	sticky_controlbox?: boolean;

	/**
	 * Raise errors for missing plugin dependencies.
	 * @default false
	 */
	strict_plugin_dependencies?: boolean;

	/**
	 * Synchronize availability with other clients.
	 * @default true
	 */
	synchronize_availability?: boolean | string;

	/**
	 * Color theme.
	 * @default 'default'
	 */
	theme?: "default" | "cyberpunk" | "dracula" | "nord";
}
