/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const content: string;
const softkeys: string;
const select: string;
const item: string;
const selected: string;

export {
	content,
	softkeys,
	select,
	item,
	selected
};

export default {
	content,
	softkeys,
	select,
	item,
	selected
};
