/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const select: string;
const wrap: string;

export {
	container,
	select,
	wrap
};

export default {
	container,
	select,
	wrap
};
